base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"

user_name: "nnoon010911"

repo_name: "cv-arxiv-daily"

show_authors: True

show_links: True

show_badge: True

max_results: 10

publish_readme: True

publish_gitpage: True

publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'

json_gitpage_path: './docs/cv-arxiv-daily-web.json'

json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'

md_gitpage_path: './docs/index.md'

md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:

  "Data-Free Knowledge Distillation":
    filters: [
      "data-free knowledge distillation",
      "data-free distillation",
      "DFKD",
      "zero-shot knowledge distillation",
      "knowledge distillation",
      "model compression"
    ]

  "Diffusion-based Distillation":
    filters: [
      "diffusion model",
      "diffusion models",
      "diffusion-based knowledge distillation",
      "synthetic data generation",
      "text-to-image generation",
      "text-to-image synthesis"
    ]

  "Vision-Language Distillation":
    filters: [
      "vision-language model distillation",
      "vision-language models",
      "CLIP distillation",
      "prompt diversification",
      "prompt learning",
      "visual prompt tuning"
    ]

  "Domain Generalization":
    filters: [
      "domain generalization",
      "domain adaptation",
      "source-free domain adaptation",
      "out-of-distribution generalization",
      "out-of-distribution detection",
      "robustness and generalization"
    ]
